name: Automatically Close Issues

on:
  issues:
    types:
      - opened

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              state: 'closed'
            });
